let selectedService='Wash & Fold';const $=id=>document.getElementById(id);function show(type){$('modal').classList.remove('hidden');if(type==='order')orderForm();if(type==='login')loginForm();if(type==='admin')adminLogin()}function hide(){$('modal').classList.add('hidden')}
function selectService(s){selectedService=s;show('order')}
function orderForm(){ $('content').innerHTML=`<h2>Book a Pickup</h2><p class="muted">No online payment. Our team will confirm your order.</p><div class="field"><label>NAME</label><input id="name" placeholder="Your name"></div><div class="field"><label>MOBILE NUMBER</label><input id="mobile" inputmode="numeric" placeholder="10-digit mobile number"></div><div class="field"><label>SERVICE</label><div class="servicePick"><button class="${selectedService==='Wash & Fold'?'active':''}" onclick="selectedService='Wash & Fold';orderForm()">Wash & Fold</button><button class="${selectedService==='Wash & Iron'?'active':''}" onclick="selectedService='Wash & Iron';orderForm()">Wash & Iron</button></div></div><div class="row"><div class="field"><label>QUANTITY (KG)</label><input id="qty" type="number" min="4" value="4"></div><div class="field"><label>PICKUP DATE</label><input id="pickup" type="date"></div></div><div class="field"><label>ADDRESS</label><textarea id="address" rows="3" placeholder="Pickup & delivery address"></textarea></div><div class="summary" id="estimate">Estimated service: ₹269</div><button class="primary" onclick="placeOrder()">Confirm Pickup</button>`;document.getElementById('qty').oninput=estimate}
function estimate(){let kg=Math.max(4,+$('qty').value||4);let p=selectedService==='Wash & Fold'?269+Math.max(0,kg-4)*69:369+Math.max(0,kg-4)*95;$('estimate').innerHTML=`Estimated service: <b>₹${p}</b><br><span class="muted">Delivery: ${p>=300?'FREE':'₹50'} · Total estimate: ₹${p+(p>=300?0:50)}</span>`}
function placeOrder(){let n=$('name').value.trim(),m=$('mobile').value.replace(/\D/g,''),a=$('address').value.trim(),kg=Math.max(4,+$('qty').value||4);if(!n||m.length!==10||!a)return alert('Please enter name, valid 10-digit mobile and address.');let service=selectedService,p=service==='Wash & Fold'?269+Math.max(0,kg-4)*69:369+Math.max(0,kg-4)*95,delivery=p>=300?0:50;fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({customerName:n,mobile:m,address:a,pickupDate:$('pickup').value,service,kg,items:[{service,kg,price:p}],subtotal:p,deliveryFee:delivery,total:p+delivery})}).then(r=>r.json()).then(o=>{$('content').innerHTML=`<h2>Order Confirmed 🎉</h2><div class="summary"><b>${o.id}</b><p>Thank you, ${o.customerName}. Your pickup request is received.</p><p>Service: ${service} · ${kg} KG</p><p>Total estimate: <b>₹${o.total}</b></p><p class="muted">Status: ${o.status}. Delivery in 2–3 days after pickup.</p></div><button class="primary" onclick="loginForm('${m}')">Track My Orders</button>`})}
function loginForm(mobile=''){$('content').innerHTML=`<h2>Track My Orders</h2><div class="field"><label>MOBILE NUMBER</label><input id="trackMobile" inputmode="numeric" value="${mobile}" placeholder="10-digit mobile number"></div><button class="primary" onclick="trackOrders()">View Orders</button><hr style="border:0;border-top:1px solid #eee;margin:25px 0"><button class="ghost" onclick="adminLogin()">Admin Login</button>`}
function trackOrders(){let m=$('trackMobile').value.replace(/\D/g,'');fetch('/api/customer/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mobile:m})}).then(r=>r.json()).then(os=>{$('content').innerHTML=`<h2>My Orders</h2>${os.length?os.map(orderCard).join(''):'<p class="muted">No orders found for this mobile number.</p>'}`})}
function orderCard(o){return `<div class="order"><div class="top"><b>${o.id}</b><span class="tag">${o.status}</span></div><p>${o.items.map(i=>`${i.service} · ${i.kg} KG`).join('<br>')}</p><p><b>₹${o.total}</b> · ${o.ready?'Ready for delivery':'In progress'}</p><small class="muted">Pickup: ${o.pickupDate||'To be confirmed'}</small></div>`}
function adminLogin(){$('content').innerHTML=`<h2>Admin Login</h2><div class="field"><label>USERNAME</label><input id="au" value="Laundry"></div><div class="field"><label>PASSWORD</label><input id="ap" type="password" placeholder="Admin password"></div><button class="primary" onclick="doAdmin()">Login</button>`}
function doAdmin(){fetch('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('au').value,password:$('ap').value})}).then(r=>r.ok?r.json():Promise.reject()).then(()=>adminPanel()).catch(()=>alert('Invalid admin login'))}
function adminPanel(){fetch('/api/admin/orders').then(r=>r.json()).then(os=>{$('content').innerHTML=`<h2>Admin Dashboard</h2><div class="adminbar"><span class="tag">${os.length} Orders</span><button class="ghost" onclick="adminPanel()">Refresh</button></div>${os.length?os.map(adminCard).join(''):'<p class="muted">No orders yet.</p>'}`})}
function adminCard(o){return `<div class="order"><div class="top"><div><b>${o.id}</b><br><span class="muted">${o.customerName} · ${o.mobile}</span></div><span class="tag">${o.status}</span></div><p>${o.items.map(i=>`${i.service} · ${i.kg} KG · ₹${i.price}`).join('<br>')}</p><p>Total: <b>₹${o.total}</b> · Delivery ₹${o.deliveryFee}</p><div class="adminbar"><select onchange="updateOrder('${o.id}',{status:this.value})"><option ${o.status==='Received'?'selected':''}>Received</option><option ${o.status==='Picked Up'?'selected':''}>Picked Up</option><option ${o.status==='Cleaning'?'selected':''}>Cleaning</option><option ${o.status==='Ready'?'selected':''}>Ready</option><option ${o.status==='Delivered'?'selected':''}>Delivered</option></select><button class="ghost" onclick="updateOrder('${o.id}',{ready:${!o.ready}})">${o.ready?'Mark Not Ready':'Mark Ready'}</button><button class="ghost" onclick="bill('${o.id}')">Bill / Signature</button></div></div>`}
function updateOrder(id,body){fetch('/api/admin/orders/'+id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}).then(adminPanel)}
function bill(id){let sig=prompt('Customer signature/name (optional):');if(sig!==null)updateOrder(id,{signature:sig})}
