const PRICES={'Wash & Fold':{minKg:4,minPrice:269,perKg:69},'Wash & Iron':{minKg:4,minPrice:369,perKg:95}};
const STATUS=['Received','Picked Up','Cleaning','Ready','Delivered'];
const j=(d,s=200,h={})=>new Response(JSON.stringify(d),{status:s,headers:{'content-type':'application/json; charset=UTF-8',...h}});
const price=(s,k)=>{const p=PRICES[s];if(!p)return null;k=Math.max(p.minKg,Number(k)||p.minKg);return p.minPrice+Math.max(0,k-p.minKg)*p.perKg};
function cookie(req,n){const x=(req.headers.get('Cookie')||'').split(';').map(v=>v.trim()).find(v=>v.startsWith(n+'='));return x?decodeURIComponent(x.slice(n.length+1)):null}
async function sig(secret,text){const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const s=await crypto.subtle.sign('HMAC',k,new TextEncoder().encode(text));return [...new Uint8Array(s)].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function admin(req,env){const t=cookie(req,'ldh_admin');if(!t||!env.ADMIN_PASSWORD)return false;const [e,s]=t.split('.');return !!e&&!!s&&Number(e)>Date.now()&&s===await sig(env.ADMIN_PASSWORD,e)}
async function api(req,env,url){
 if(!env.DB)return j({error:'Database is not connected yet.'},500);
 if(url.pathname==='/api/prices'&&req.method==='GET')return j(PRICES);
 if(url.pathname==='/api/orders'&&req.method==='POST'){const b=await req.json(),name=String(b.customerName||'').trim(),mobile=String(b.mobile||'').replace(/\D/g,''),address=String(b.address||'').trim(),service=String(b.service||''),kg=Math.max(4,Number(b.kg)||4);if(!name||mobile.length!==10||!address||!PRICES[service])return j({error:'Please enter name, valid 10-digit mobile, address and service.'},400);const subtotal=price(service,kg),deliveryFee=subtotal>=300?0:50,total=subtotal+deliveryFee,id='LDH-'+crypto.randomUUID().slice(0,8).toUpperCase(),createdAt=new Date().toISOString();await env.DB.prepare("INSERT INTO orders (id,customer_name,mobile,address,pickup_date,service,kg,subtotal,delivery_fee,total,status,ready,signature,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,'Received',0,'',?)").bind(id,name,mobile,address,String(b.pickupDate||''),service,kg,subtotal,deliveryFee,total,createdAt).run();return j({id,customerName:name,mobile,address,pickupDate:String(b.pickupDate||''),service,kg,subtotal,deliveryFee,total,status:'Received',ready:false,createdAt})}
 if(url.pathname==='/api/customer/orders'&&req.method==='POST'){const b=await req.json(),m=String(b.mobile||'').replace(/\D/g,'');if(m.length!==10)return j({error:'Enter a valid 10-digit mobile number.'},400);const {results}=await env.DB.prepare('SELECT * FROM orders WHERE mobile=? ORDER BY created_at DESC LIMIT 20').bind(m).all();return j(results.map(o=>({...o,customerName:o.customer_name,pickupDate:o.pickup_date,deliveryFee:o.delivery_fee,ready:!!o.ready})))}
 if(url.pathname==='/api/admin/login'&&req.method==='POST'){const b=await req.json();if(!env.ADMIN_PASSWORD||String(b.username||'')!=='Laundry'||String(b.password||'')!==env.ADMIN_PASSWORD)return j({error:'Invalid admin login.'},401);const e=String(Date.now()+43200000);return j({ok:true},200,{'Set-Cookie':`ldh_admin=${encodeURIComponent(e+'.'+await sig(env.ADMIN_PASSWORD,e))}; Max-Age=43200; Path=/; HttpOnly; Secure; SameSite=Lax`})}
 if(url.pathname==='/api/admin/logout'&&req.method==='POST')return j({ok:true},200,{'Set-Cookie':'ldh_admin=; Max-Age=0; Path=/; HttpOnly; Secure; SameSite=Lax'});
 if(url.pathname==='/api/admin/orders'&&req.method==='GET'){if(!await admin(req,env))return j({error:'Admin login required.'},401);const {results}=await env.DB.prepare('SELECT * FROM orders ORDER BY created_at DESC LIMIT 500').all();return j(results.map(o=>({...o,customerName:o.customer_name,pickupDate:o.pickup_date,deliveryFee:o.delivery_fee,ready:!!o.ready})))}
 const m=url.pathname.match(/^\/api\/admin\/orders\/([^/]+)$/);if(m&&req.method==='PATCH'){if(!await admin(req,env))return j({error:'Admin login required.'},401);const b=await req.json(),sets=[],v=[];if(b.status&&STATUS.includes(b.status)){sets.push('status=?');v.push(b.status)}if(typeof b.ready==='boolean'){sets.push('ready=?');v.push(b.ready?1:0)}if(typeof b.signature==='string'){sets.push('signature=?');v.push(b.signature.slice(0,200))}if(!sets.length)return j({error:'Nothing to update.'},400);v.push(m[1]);const r=await env.DB.prepare(`UPDATE orders SET ${sets.join(',')} WHERE id=?`).bind(...v).run();return r.meta.changes?j({ok:true}):j({error:'Order not found.'},404)}
 return j({error:'Not found.'},404)
}
export default{async fetch(req,env){const u=new URL(req.url);return u.pathname.startsWith('/api/')?api(req,env,u):env.ASSETS.fetch(req)}};
