name = "laundry-desire-hub-dry-cleaning2"
main = "worker.js"
compatibility_date = "2026-08-29"

[assets]
directory = "./public"

[[d1_databases]]
binding = "DB"
database_name = "laundry-desire-hub-db"
database_id = "c659f4ea-f32e-46c9-b324-913081e5dd63"
