name = "laundry-desire-hub"
main = "app.js"
compatibility_date = "2026-08-29"

[assets]
directory = "./public"

[[d1_databases]]
binding = "DB"
database_name = "laundry-desire-hub-db"
database_id = "YAHAN_APNI_D1_DATABASE_ID_DALO"
